from Listas import LinkedList

l = LinkedList ()
print (f"L esta vacia ? {l.is_empy()} ")
l.append(10)
l.append(5)
l.append(6)
l.append(20)
print (f"L esta vacia ? {l.is_empy()} ")
l.transversal()
l.remove(10)
print ("\n")
l.transversal()
print ("\n")
l.prepend (3)
l.transversal()
x = l.tail ()
print ("\n-----------------")
print (x.data)
print (l.get)
